// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { AboutPage } from "about_page.slint";
import { ControlsPage,ControlsPageAdapter } from "controls_page.slint";
import { SettingsPage } from "settings_page.slint";
import { BoardPage } from "board_page.slint";
import { FunctionsPage, FunctionsPageAdapter } from "functions_page.slint";
import { OtherPage } from "other_page.slint";

export { AboutPage, ControlsPage, SettingsPage, BoardPage, OtherPage, FunctionsPage, FunctionsPageAdapter,ControlsPageAdapter }