// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { AboutPage, ControlsPage, SettingsPage, BoardPage, FunctionsPage, FunctionsPageAdapter, ControlsPageAdapter,OtherPage } from "pages/pages.slint";
import { TestSettings } from "test_settings.slint";
import { SideBar } from "side_bar.slint";

export { FunctionsPageAdapter,ControlsPageAdapter }

export component MainWindow inherits Window {

    in-out property <string> test;

    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("rk flash tool");
    icon: @image-url("logo/slint-logo-small-light.png");

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("DEV FLASH MENU");
            //model: [@tr("Menu" => "Controls"), @tr("Menu" => "Board"), @tr("Menu" => "Functions"), @tr("Menu" => "Other"), @tr("Menu" => "Settings"), @tr("Menu" => "About")];
            model: [@tr("Menu" => "Controls"), @tr("Menu" => "Demo"), @tr("Menu" => "Settings"), @tr("Menu" => "About")];
        }

        if(side-bar.current-item == 0) : ControlsPage {}
        //if(side-bar.current-item == 1) : BoardPage {}
        if(side-bar.current-item == 1) : FunctionsPage {}
        //if(side-bar.current-item == 3) : OtherPage {}
        if(side-bar.current-item == 2) : SettingsPage {}
        if(side-bar.current-item == 3) : AboutPage {}
    }
}
